name: CI/CD PRO
run-name: ${{ github.workflow }} by @${{ github.actor }}

on:
  create:
    branches:
      - master
jobs:
  pro:
    if: startsWith(github.ref, 'refs/tags/v') && github.event.ref_type == 'tag'
    name: PRO
    runs-on: ubuntu-latest
    environment:
        name: PRO
    timeout-minutes: 120
    steps:
      - name: Checkout code tag
        uses: actions/checkout@v4
        with:
          ref:  ${{ github.ref }}
