name: CI/CD PRO
run-name: ${{ github.workflow }} by @${{ github.actor }}

on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+
    branches: main

jobs:
  pro:
    name: PRO
    runs-on: ubuntu-latest
    environment:
        name: PRO
    timeout-minutes: 120
    steps:
      - name: Checkout code tag
        uses: actions/checkout@v4
        with:
          ref:  ${{ github.ref }}
