name: CI/CD
run-name: ${{ github.workflow }} by @${{ github.actor }}

on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+

jobs:

  parallel-job:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: |
          echo "{{ toJson(github) }}" | jq


  # job-on-dev:
  #   if: startsWith(github.ref, 'refs/tags/') && github.base_ref == 'dev'
  #   runs-on: ubuntu-latest
  #   environment: PRE
  #   steps:
  #     - name: Checkout code tag
  #       uses: actions/checkout@v4
  #       with:
  #         ref:  ${{ github.ref }}

  # job-on-main:
  #   if: startsWith(github.ref, 'refs/tags/') && github.base_ref == 'main'
  #   runs-on: ubuntu-latest
  #   environment: PRO
  #   steps:
  #     - name: Checkout code tag
  #       uses: actions/checkout@v4
  #       with:
  #         ref:  ${{ github.ref }}