name: CI/CD
run-name: ${{ github.workflow }} by @${{ github.actor }}

on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: ${{ github.event.base_ref == 'refs/heads/main' && 'PRO' || 'PRE' }}
    env:
      ENTORNO: ${{ github.event.base_ref == 'refs/heads/main' && 'PRO' || 'PRE' }}
    steps:
      - run: echo $ENTORNO
      - name: Checkout code tag
        uses: actions/checkout@v4
        with:
          ref:  ${{ github.ref }}
